// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH7gGZBrpKqS8nebAB1sdkwuxhlEDUWCk',
    appId: '1:66590052798:web:d04ead8c78b848980ea9ef',
    messagingSenderId: '66590052798',
    projectId: 'vida-doe-app',
    authDomain: 'vida-doe-app.firebaseapp.com',
    storageBucket: 'vida-doe-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIuQIAv541ZTnnoyZzLMp9Xv8Hn9q_7eM',
    appId: '1:66590052798:android:4dad5c70b72782170ea9ef',
    messagingSenderId: '66590052798',
    projectId: 'vida-doe-app',
    storageBucket: 'vida-doe-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUblsdStyhUb8OlU66pPv1W-ozH7y6KdA',
    appId: '1:66590052798:ios:f1d049a8c8f5590b0ea9ef',
    messagingSenderId: '66590052798',
    projectId: 'vida-doe-app',
    storageBucket: 'vida-doe-app.appspot.com',
    iosClientId: '66590052798-a8botskoensuo82dqjde213vnobbap53.apps.googleusercontent.com',
    iosBundleId: 'com.doevida.doeVida',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUblsdStyhUb8OlU66pPv1W-ozH7y6KdA',
    appId: '1:66590052798:ios:8f1cec092954de980ea9ef',
    messagingSenderId: '66590052798',
    projectId: 'vida-doe-app',
    storageBucket: 'vida-doe-app.appspot.com',
    iosClientId: '66590052798-ms30iiudmkkiseid575cj38e1nhkebci.apps.googleusercontent.com',
    iosBundleId: 'com.doevida.doeVida.RunnerTests',
  );
}
